### PR TITLE
Introduce jvm-engine buildpack

### PR DESCRIPTION
**Pull request by schneems**
The existing heroku/jvm buildpack both provides and requires itself unconditionally. That means if you put `heroku/jvm` in a build order it will always run even if it is specified as optional. 

What does that mean? Most build packs will always provide a resource (like "ruby") but only require it if it has a positive signal (such as presence of a Gemfile on disk). The JVM buildpack is different because the JVM ecosystem can be used with wildly different JVM applications, many of them do not have a single file that would indicate it needs the JDK. To support this set of various use cases it always installs the JVM.

This always-install behavior is a problem for the Ruby buildpack due to JRuby support. JRuby is provided by the same buildpack as Ruby the only difference is that it needs the JVM installed (and it downloads a jruby binary from S3). To install the JVM the heroku/ruby builder has `heroku/jvm` specified as an optional dependency. Due to existing behavior that means the JVM is installed for ALL ruby applications even if is not using the JVM. This eats up disk space and takes up build time.

There are possible fixes:

- A: Introduce an only-provide buildpack and change the existing `heroku/jvm` buildpack to be a no-op that always requires the other buildpack. Then the `heroku/ruby` (and any other build packs) can optionally depend on the JVM through the regular require interface.
- B: Introduce a new JRuby buildpack that fails to detect if jruby is not detected (via inspecting the Gemfile.lock). Use this to make a new group along with the heroku/jvm and place that group above the existing heroku/ruby group. Remove the `heroku/jvm` group from the heroku/ruby group. This would have the effect of only installing the JVM for JRuby apps.
- C: Edit: Only require jvm when a valid file is matched on disk (https://github.com/heroku/buildpacks-jvm/pull/541) 
- D: Some other option

This PR implements option A. It moves the existing logic to a `heroku/jvm-engine` buildpack and removes its `require`. Then the `heroku/jvm` buildpack is stripped of all logic and all it does is `require` the jvm provided by the `heroku/jvm-engine`.

The upside of this approach is that any buildpack can use the `heroku-jvm-engine` much like the `heroku-nodejs-engine` to install the JVM optionally. As long as the existing `heroku/jvm` builder is updated with both build packs then this should be a non-breaking change save if someone was using the `heroku/jvm` buildpack directly (not through the builder), they'll now need to also add the `heroku/jvm-engine` buildpack as well.

## Other thoughts

This interface is really funky. It's a very-round about way of expressing what should be a seemingly common use case. Having the builder separated from the buildpack and provide/require be based on a string instead of a specific resource leads to very difficult to reason about resolution logic. 

Another option (but it won't meet our timescale) could be a change to the builder spec: For instance we could expose the `optional` flag to a buildpack in the detect phase to let a buildpack know if it is being treated as optional or not and change its behavior accordingly.

Longer term it's worth experimenting with alternative interfaces that we could build on top of these three primitives (builder, buildpack, provide/require build plans). I've proposed a theoretical middleware like interface (Rack middleware would be my design inspiration as I come from Ruby) but I've not sketched up any kind of implementation ideas.

### CODE REVIEW

**Comment by edmorley** [comment]
> C: Some other option

Another option would be to not add another buildpack, but instead:
* Change the `heroku/jvm` buildpack so it only requires itself if some Java-related files are found
* Make the `heroku/java` buildpack and other Java-related buildpacks explicitly require the JVM (just in case no Java related files are found in the project)
* Make the Ruby buildpack conditionally require the JVM if the Ruby project is found to be a JRuby project

The only disadvantage of this approach would be that anyone using `heroku/jvm` directly (and not via `heroku/java` etc) would need to ensure they have a known Java-related files in their app source, or `heroku/jvm` would no longer pass detection.

However, to me this still seems preferable to creating an empty buildpack just for the sake of requires/provides.

**Review by edmorley — COMMENTED** [review]
Deferring review to Manuel

**Comment by schneems** [comment]
> Change the heroku/jvm buildpack so it only requires itself if some Java-related files are found

Manuel had this to say before "There is no "Java package manager" like there is for other languages. Many Java customers also install the JVM standalone without using any package manager. The last point is actually the main reason for requiring itself: sometimes it's the only thing a customer wants, there is no other buildpack that could ever require it."

To that end, one of the ways I think about usability is the number of steps something takes. I.e. declaring "use heroku/jvm as a buildpack" is one step and so is setting an env var or writing a file to disk. Another option could be:

- Introduce a pseudo standard for declaring your app needs/wants the JVM

This is somewhat similar to the history of `Procfile`, and we also have `app.json` (maybe that could be utilized?) I would ideally propose something that gets checked in with the repo. Possibly just an empty `system.properties` file. Then we could have the `jvm` buildpack execute for every build group optionally, much like nodejs. 

> Make the Ruby buildpack conditionally require the JVM if the Ruby project is found to be a JRuby project

I don't think that's possible without a second builder. It's what we're doing today:

- https://github.com/heroku/builder/blob/ec92d59f464e1e2e32638e9808c3c767ea1022bd/builder-22/builder.toml#L69-L72
- https://github.com/heroku/buildpacks-ruby/blob/2022e5d2fea4acb3d082e121d95b99f8382da85e/buildpacks/ruby/src/main.rs#L52-L54

I intend(ed) to make a second PR to the Ruby buildpack to explore what it looks like to have a `jruby-detect` (or similar buildpack) that could be used to generate a second grouping that is non-optional. Something like this:

```
[[order]]
  [[order.group]] # Proposed jruby buildpack ordering
    id = "heroku/nodejs-engine"
    version = "0.8.24"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "0.4.4"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "1.0.10"
    optional = true
  [[order.group]] # Fails if does not detect jruby in order
    id = "heroku/jruby-detect"
    version = "2.0.0"
  [[order.group]]
    id = "heroku/ruby"
    version = "2.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true
  [[order.group]] # Current heroku/ruby buildpack minus the JVM buildpack
    id = "heroku/nodejs-engine"
    version = "0.8.24"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "0.4.4"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]] # Current buildpack grouping without jvm
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "1.1.0"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "1.1.0"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.0.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true
```

Though now that I'm thinking of implementation, I see a failure mode: 

- If the JRuby group fails detection (due to some bug) then it would still pass detection for the regular ruby group, but the JVM wouldn't be installed yet. I guess that's not technically any different than what I've got today and I'm not doing anything to improve that failure mode. So while that behavior might be surprising, it's not worse than what we've got today.

**Comment by edmorley** [comment]
> Manuel had this to say before "There is no "Java package manager" like there is for other languages. Many Java customers also install the JVM standalone without using any package manager. The last point is actually the main reason for requiring itself: sometimes it's the only thing a customer wants, there is no other buildpack that could ever require it."

Yeah I wasn't meaning check for a package manager, but instead for say the presence of `.jar` files in the app source, or say a `system.properties` file (given that specifying an explicit JVM version should really be best practice, so if someone wants to run a JVM without a package manager, then it seems reasonable to say they have to have a `system.properties` file perhaps, if the `.jar` file idea isn't viable etc?).

**Comment by schneems** [comment]
Here's a spike on that idea @edmorley https://github.com/heroku/buildpacks-jvm/pull/541

**Comment by Malax** [comment]
Apart from issue I see with the `engine` naming, I think we should invert this and create an explicit `jvm-standalone` buildpack that users can opt-in to if they need the JVM for any reason when it's not required by another buildpack. This keeps things simple both for us implementation wise and the user. 

I have the required changes locally already and will open a PR soon that implements ☝🏻. This should unblock @schneems' use-case with the Ruby buildpack.

I'm closing this in favor of the strategy I outlined before. Feel free to re-open if you disagree.

**Comment by schneems** [comment]
Linking PRs https://github.com/heroku/buildpacks-jvm/pull/545

**Pull request closed without merging**
