### PR TITLE
Change requiring JVM to a use file based acceptlist

### PR DESCRIPTION
**Pull request by schneems**
There are several high quality signals that an application needs the JVM (looking at the `sbt` and `maven` buildpacks) and we can also add more (such as checking for a `system.properties` file). Developers who want to opt into the behavior that don't have one of these common files will need to add one.

This change is breaking for developers relying on the current "always provide" logic.

## Approach

The detect logic for buildpacks (sbt and maven) are moved to the shared code crate and they can be re-used by the `heroku/jvm` buildpack. That means any app that currently uses `heroku/java` or `heroku/scala` are guaranteed to have the JVM installed by `heroku/jvm` in addition the following files are also checked:

- system.properties
- *.war // TODO: Add glob

### CODE REVIEW

**Review by Malax — COMMENTED** [review]
Hi! Thanks for sketching this out!

I think the main issue with this approach is that the users that want to use the JVM buildpack standalone do so because they want to use an unsupported JVM language on the platform. We don't have detection for these as they are unsupported so that whole use-case doesn't work anymore. 

Regardless how thorough our heuristic will be, there will always be cases where customers want OpenJDK installed that we cannot detect - it's a very diverse ecosystem. For these cases, I'd like to go the explicit route and force users to explicitly set something like `heroku/jvm-standalone` as the buildpack.

This removes the need for complex solutions and is more reliable for users that need it.

**Comment by Malax** [comment]
I'm closing this (but leaving the branch around) as I don't think this strategy will work regardless of implementation details (see review comment). If you want to continue with this, feel free to re-open the PR. :) If you agree that we should stop here, delete the branch :)

**Comment by schneems** [comment]
> Regardless how thorough our heuristic will be, there will always be cases where customers want OpenJDK installed that we cannot detect - it's a very diverse ecosystem. For these cases, I'd like to go the explicit route and force users to explicitly set something like heroku/jvm-standalone as the buildpack.

My hope would be that there might be some file that they don't find offensive to add to their project even if it's essentially empty. For example, Rails users must have a `package.json` file even if it just contains `{}`. I would hope that they would be willing to add **A** file from their list to their project even if it's not strictly necessary. I'll defer to your expertise and experience. Looking at https://github.com/heroku/buildpacks-jvm/pull/545 now.

**Comment by schneems** [comment]
Superseded by #546

**Pull request closed without merging**
