### PR TITLE
Use Cargo workspace

### PR DESCRIPTION
**Pull request by Malax**
Use a Cargo workspace, nothing more to say really. :)

### CODE REVIEW

**Review by colincasey — APPROVED** [review]

**Review by joshwlewis — APPROVED** [review]
This looks familiar!

**Review by edmorley — COMMENTED** [review]
Don't forget to update Dependabot too :-)
https://github.com/heroku/buildpacks-jvm/blob/428f2f3fa12492a04834b5ca6c4ddad6b5477f9d/.github/dependabot.yml#L10-L11

There's an existing GUS issue for this work, if you wanted to link it:
GUS-W-10436039.

**Comment by Malax** [comment]
@edmorley Thanks!

**Comment by Malax** [comment]
Rebased onto main after fixing CI.

**Pull request merged**
